set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#738696 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#7B848E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#5E6873 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#738696 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#0F1924 guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#7B848E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#687987 guibg=NONE guisp=#687987 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#D6DDE1 guibg=NONE guisp=#D6DDE1 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#97A2AA guibg=NONE guisp=#97A2AA blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#7D91A1 guibg=NONE guisp=#7D91A1 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#738591 guibg=#5E6873 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#9EA2A9 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#687987 guibg=#5E6873 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#687987 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#97A2AA guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#738591 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#97A2AA guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#687987 guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#687987 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#738696 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#97A2AA guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#5E6873 guibg=#738696 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#9EA2A9 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C2C4C7 guibg=#9EA2A9 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#5E6873 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#97A2AA guibg=NONE guisp=#9EA2A9 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#7D91A1 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#7B848E guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#0F1924 guibg=#D6DDE1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#0F1924 guibg=#97A2AA guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#0F1924 guibg=#738591 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#0F1924 guibg=#CCC7D1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#0F1924 guibg=#687987 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#0F1924 guibg=#738696 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#5E6873 guibg=#738696 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#9EA2A9 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#738591 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#7B848E guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#9EA2A9 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#687987 guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#738696 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C2C4C7 guibg=#97A2AA guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#7B848E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#9EA2A9 guibg=#7D91A1 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#7B848E guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#687987 guibg=NONE guisp=#687987 blend=NONE gui=underline
highlight SpellCap guifg=#7D91A1 guibg=NONE guisp=#7D91A1 blend=NONE gui=underline
highlight SpellLocal guifg=#D6DDE1 guibg=NONE guisp=#D6DDE1 blend=NONE gui=underline
highlight SpellRare guifg=#CCC7D1 guibg=NONE guisp=#CCC7D1 blend=NONE gui=underline
highlight Statement guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C2C4C7 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#7B848E guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#738591 guibg=#738591 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#7D91A1 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#9EA2A9 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#9EA2A9 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#738591 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#7D91A1 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#0F1924 guibg=#7B848E guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C2C4C7 guibg=#97A2AA guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C2C4C7 guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#7B848E guibg=#0F1924 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#728492 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#738591 guibg=#5E6873 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#687987 guibg=#5E6873 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#CCC7D1 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#738591 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#D6DDE1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#7D91A1 guibg=#5E6873 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#5E6873 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#97A2AA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#7D91A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#687987 guibg=NONE guisp=NONE blend=NONE gui=NONE
